version: '3.5'
services:
  api:
    container_name: haskell-rest-api
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/project
    environment:
      - DB_HOST=api-postgres
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=postgres
    command:
      - /usr/local/bin/api
    networks:
      - haskell-api
  postgres:
    container_name: api-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"
    ports:
      - "46000:5432"
    restart: unless-stopped
    networks:
      - haskell-api

volumes:
  postgres_data:

networks:
  haskell-api:
    name: haskell-api
