name: haskell-rest-api-example
version: 0.1.0.0
github: "drmick/haskell-rest-api"
license: BSD3
author: "Maksim Greshnyakov"
maintainer: "mgreshnyakov@protonmail.com"

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/drmick/haskell-rest-api#readme>

dependencies:
  - base >= 4.7 && < 5
  - wai >= 3.0.2 # wai server
  - HTTP >= 4000.2.18
  - http-types >= 0.8.5 # types
  - warp >= 3.3.20 # web server
  - scotty >= 0.12 # router
  - wai-extra >= 3.1.8 # extra middlewares for wai
  - aeson >= 2.0.3.0 # json serializator
  - text >= 0.11
  - mr-env >= 0.1.0.4 # env
  - postgresql-simple >= 0.6.4 # postgres client
  - bytestring >= 0.1
  - resource-pool >= 0.2.3.2 # connection pool for db
  - wai-cors >= 0.2.7 # cors config
  - MissingH >= 1.3.0.1 # md5 encoder

library:
  source-dirs:
    - lib

executables:
  api:
    main: Main.hs
    source-dirs:
      - app
      - app/model
      - app/repository
      - app/service
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-rest-api-example